defaults:
  - _self_
  - run: proposed-qwen3-8b-gsm8k

run: proposed-qwen3-8b-gsm8k
results_dir: "results"
mode: "full"

wandb:
  entity: airas
  project: 2026-02-09
  mode: online

optuna:
  n_trials: 0

hydra:
  run:
    dir: .
